name: Greenhouse GitOps Deploy

on:
  push:
    paths:
      - 'greenhouse/**'

jobs:
  trigger-awx:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AWX Workflow
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.AWX_TOKEN }}" \
            -d '{"extra_vars": {}}' \
            https://awx-server.taileaaeb7.ts.net/api/v2/workflow_job_templates/16/launch/
